### ISSUE TITLE
Remove `gh-extension` topic from this repository

### ISSUE THREAD

**Issue by mislav** [abdfnx/resto#130]
Hi, thanks for sharing a cool project with the world, and for maintaining a GitHub CLI extension.

Your repository `abdfnx/gh-resto` is an installable CLI extension and has the `gh-extension` repository topic, which helps it get discovered by `gh extension search` command. We use the topic to discover public extensions made by the community. All is good here!

However, this repository `abdfnx/resto` is _not_ an installable CLI extension, and therefore should not have `gh-extension` topic. By removing the topic from this repo, you could help make `gh extension search` more efficient. Thank you!

**Comment by abdfnx** [comment]
Hi @mislav , no problem
