### ISSUE TITLE
resto crashing after change arugments values

### ISSUE THREAD

**Issue by david-tomson** [abdfnx/resto#3]
when I change an argument in `resto`, it's crashed

![issue](https://user-images.githubusercontent.com/90329278/146005645-85691384-8438-4f05-a75d-fabc74272624.gif)

so we've to fix it

**Comment by abdfnx** [comment]
yeah, I notice this problem from 1 day, I don't know where's the bug, but I'll found it.

**Comment by abdfnx** [comment]
I found the solution, the bug in [`core/layout/app.go#193-203`](https://github.com/abdfnx/resto/blob/a679312a0746a4a90ce89fc9238ccb080d28fe3e/core/layout/app.go#L193-L203)

**Comment by abdfnx** [comment]
fixed
