### ISSUE TITLE
error sending request

### ISSUE THREAD

**Issue by Cris-lml007** [abdfnx/resto#90]
I am trying to make requests to my localhost but it gives me this error, how can I solve it.  
![image](https://user-images.githubusercontent.com/83845332/215359750-edac74f9-a65b-4568-8d89-e9eb28bb0773.png)

**Comment by abdfnx** [comment]
hi @Cris-lml007, you need to fix your localhost url, like this **http://localhost:3000**

**Comment by Cris-lml007** [comment]
Thank you very much, I managed to make it work.
